import 'dart:convert';
import 'package:dartssh2/dartssh2_otp.dart';

Future<void> main() async {
  const sshHost = 'pctunnel.public';
  const sshUser = 'daq_user';
  const sshPassword = 'mypassword';
  const daqHost = 'daqserver.local';
  const daqPort = 7106;

  // In Flutter the token is generated by app
  final otpToken = '123456'; // Static example

  print('Connecting to $sshHost...');
  final socket = await SSHSocket.connect(sshHost, 22);
  final ssh = SSHClient(socket, username: sshUser);

  // Outside domain → OTP
  await ssh.authPasswordWithOtp(sshUser, sshPassword, otpToken);

  // Insde domain → only password
  // await ssh.authPassword(sshUser, sshPassword);

  print('Authentication successful. Opening tunnel...');
  final tunnel = await ssh.forwardSocket(daqHost, daqPort);

  tunnel.write('{"command":"status"}\n');
  print('Command sent to DAQ server.');

  tunnel.stream.listen((data) async {
    final response = utf8.decode(data);
    print('Response: $response');

    if (response.contains('"status"') || response.contains('"ok"')) {
      print('Closing tunnel...');
      await tunnel.close();
      await ssh.close();
      print('Tunnel closed.');
    }
  });
}
