import 'package:dartssh2/dartssh2.dart';

extension SSHClientOtpExtension on SSHClient {
  /// Authentication  SSH with password + OTP
  ///
  ///  This function is usede if server require 2FA.
  /// [otpToken] is the code OTP  generated by the client Flutter.
  Future<void> authPasswordWithOtp(
    String username,
    String password,
    String otpToken,
  ) async {
    // Prima autenticazione con password
    await authPassword(username, password);

    // Poi invio del token OTP (keyboard-interactive)
    await authKeyboardInteractive(
      username,
      onPrompt: (prompts) async {
        if (prompts.isNotEmpty) {
          return [otpToken];
        }
        return [];
      },
    );
  }
}
